## Roy Real Estate - Price Predictor

@[Kushal Raj Roy](https://github.com/kushalrajroy/)

This is a project about the prices correlated with other important factors associated within the neighborhood. it is my first machine learning project assumed with the skretch given on [youtube](https://www.youtube.com/watch?v=iIkJrwVUl1c&t=2097s)

### 1.1 Import Libraries

In [1]:
#import the necessary libraries for our machine learning data analysis

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#import the dataset using pandas read_csv module

housing = pd.read_csv('data.csv')
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [3]:
#plot histgram to check the each columns distribution

#housing.hist(bins=50, figsize=(20,15))

In [4]:
#create a train_test_split function.


def train_test_split(data, test_ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data)*test_ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    
    return data.iloc[test_indices], data.iloc[train_indices]

In [5]:
test_set, train_set = train_test_split(housing, 0.2)

In [6]:
#similarly train_test_split function can be automaticallt imported from sklearn model_selection
from sklearn.model_selection import train_test_split

test_set, train_set = train_test_split(housing, test_size=0.2, random_state=42)
print(f"Rows in train set: {train_set}\n Rows in test set: {test_set}\n")

Rows in train set:          CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD  TAX  \
173   0.09178   0.0   4.05     0  0.510  6.416   84.1  2.6463    5  296   
274   0.05644  40.0   6.41     1  0.447  6.758   32.9  4.0776    4  254   
491   0.10574   0.0  27.74     0  0.609  5.983   98.8  1.8681    4  711   
72    0.09164   0.0  10.81     0  0.413  6.065    7.8  5.2873    4  305   
452   5.09017   0.0  18.10     0  0.713  6.297   91.8  2.3682   24  666   
..        ...   ...    ...   ...    ...    ...    ...     ...  ...  ...   
412  18.81100   0.0  18.10     0  0.597  4.628  100.0  1.5539   24  666   
436  14.42080   0.0  18.10     0  0.740  6.461   93.3  2.0026   24  666   
411  14.05070   0.0  18.10     0  0.597  6.657  100.0  1.5275   24  666   
86    0.05188   0.0   4.49     0  0.449  6.015   45.1  4.4272    3  247   
75    0.09512   0.0  12.83     0  0.437  6.286   45.0  4.5026    5  398   

     PTRATIO       B  LSTAT  MEDV  
173     16.6  395.50   9.04  23.6  
274     

In [7]:
#sometimes we dont get exact shuffled value. to make it more accurate we can use stratified shuffle split function from sklearn model selection

from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1, test_size = 0.2, random_state=42)

for train_index, test_index in split.split(housing, housing['CHAS']):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]
                                           



In [8]:
#check the value counts
strat_train_set['CHAS'].value_counts(), strat_test_set['CHAS'].value_counts()

(0    376
 1     28
 Name: CHAS, dtype: int64,
 0    95
 1     7
 Name: CHAS, dtype: int64)

## Looking for Correlations

In [9]:
#pandas dataframe has corr function to calculate correlation in data

corr_matrix = housing.corr()
corr_matrix

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
CRIM     1.000000 -0.200469  0.406583 -0.055892  0.420972 -0.219433  0.352734   
ZN      -0.200469  1.000000 -0.533828 -0.042697 -0.516604  0.311173 -0.569537   
INDUS    0.406583 -0.533828  1.000000  0.062938  0.763651 -0.394193  0.644779   
CHAS    -0.055892 -0.042697  0.062938  1.000000  0.091203  0.091468  0.086518   
NOX      0.420972 -0.516604  0.763651  0.091203  1.000000 -0.302751  0.731470   
RM      -0.219433  0.311173 -0.394193  0.091468 -0.302751  1.000000 -0.240286   
AGE      0.352734 -0.569537  0.644779  0.086518  0.731470 -0.240286  1.000000   
DIS     -0.379670  0.664408 -0.708027 -0.099176 -0.769230  0.203507 -0.747881   
RAD      0.625505 -0.311948  0.595129 -0.007368  0.611441 -0.210718  0.456022   
TAX      0.582764 -0.314563  0.720760 -0.035587  0.668023 -0.292794  0.506456   
PTRATIO  0.289946 -0.391679  0.383248 -0.121515  0.188933 -0.357612  0.261515   
B       -0.385064  0.175520 -0.356977  0.048788 -0.380051  0.128107 -0.273534   
LSTAT    0.455621 -0.412995  0.603800 -0.053929  0.590879 -0.615721  0.602339   
MEDV    -0.388305  0.360445 -0.483725  0.175260 -0.427321  0.696169 -0.376955   

              DIS       RAD       TAX   PTRATIO         B     LSTAT      MEDV  
CRIM    -0.379670  0.625505  0.582764  0.289946 -0.385064  0.455621 -0.388305  
ZN       0.664408 -0.311948 -0.314563 -0.391679  0.175520 -0.412995  0.360445  
INDUS   -0.708027  0.595129  0.720760  0.383248 -0.356977  0.603800 -0.483725  
CHAS    -0.099176 -0.007368 -0.035587 -0.121515  0.048788 -0.053929  0.175260  
NOX     -0.769230  0.611441  0.668023  0.188933 -0.380051  0.590879 -0.427321  
RM       0.203507 -0.210718 -0.292794 -0.357612  0.128107 -0.615721  0.696169  
AGE     -0.747881  0.456022  0.506456  0.261515 -0.273534  0.602339 -0.376955  
DIS      1.000000 -0.494588 -0.534432 -0.232471  0.291512 -0.496996  0.249929  
RAD     -0.494588  1.000000  0.910228  0.464741 -0.444413  0.488676 -0.381626  
TAX     -0.534432  0.910228  1.000000  0.460853 -0.441808  0.543993 -0.468536  
PTRATIO -0.232471  0.464741  0.460853  1.000000 -0.177383  0.374044 -0.507787  
B        0.291512 -0.444413 -0.441808 -0.177383  1.000000 -0.366087  0.333461  
LSTAT   -0.496996  0.488676  0.543993  0.374044 -0.366087  1.000000 -0.737663  
MEDV     0.249929 -0.381626 -0.468536 -0.507787  0.333461 -0.737663  1.000000

In [10]:
#looking for correlation in median values of owner occupied homes in 1000$

corr_matrix['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RM         0.696169
ZN         0.360445
B          0.333461
DIS        0.249929
CHAS       0.175260
AGE       -0.376955
RAD       -0.381626
CRIM      -0.388305
NOX       -0.427321
TAX       -0.468536
INDUS     -0.483725
PTRATIO   -0.507787
LSTAT     -0.737663
Name: MEDV, dtype: float64

In [11]:
#we will apply pandas plotting's scatter_matrix

#from pandas.plotting import scatter_matrix
#attributes= ['MEDV', 'RM', 'ZN', 'LSTAT']
#scatter_matrix(housing[attributes], figsize = (20,15))


In [12]:
#from the scatter plot a strong correlations has been noticed between MEDV & RM /LSTAT & MEDV

#housing.plot(kind= "scatter", x = 'RM', y='MEDV', alpha=1, figsize= (20,10))

In [13]:
housing['TAXRM'] = housing['TAX']/ housing['RM']

In [14]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV      TAXRM  
0  396.90   4.98  24.0  45.019011  
1  396.90   9.14  21.6  37.688834  
2  392.83   4.03  34.7  33.681280  
3  394.63   2.94  33.4  31.723350  
4  396.90   5.33  36.2  31.061984

In [15]:

#housing.plot(kind= "scatter", x = 'TAXRM', y='MEDV', alpha=1, figsize= (12,8))

###  Handling missing attributes

In [16]:
housing = strat_train_set.drop("MEDV", axis=1)
housing_labels = strat_train_set["MEDV"].copy()

In [17]:
 #TO take care of missing attributes, you have three options.
    
    #    1. Get rid of the missing data points
    #    2. Get rid of the whole attribute/column
    #    3. Set the valur to some value(0, mean or median)

In [18]:
a = housing.dropna(subset=['RM'], inplace= False) # Option:1 
a.shape

(399, 13)

In [19]:
housing.drop("RM", axis=1) #option: 2

#note that the orginal dataframe

CRIM    ZN  INDUS  CHAS    NOX   AGE     DIS  RAD  TAX  PTRATIO  \
254  0.04819  80.0   3.64     0  0.392  32.0  9.2203    1  315     16.4   
348  0.01501  80.0   2.01     0  0.435  29.7  8.3440    4  280     17.0   
476  4.87141   0.0  18.10     0  0.614  93.6  2.3053   24  666     20.2   
321  0.18159   0.0   7.38     0  0.493  54.3  4.5404    5  287     19.6   
326  0.30347   0.0   7.38     0  0.493  28.9  5.4159    5  287     19.6   
..       ...   ...    ...   ...    ...   ...     ...  ...  ...      ...   
155  3.53501   0.0  19.58     1  0.871  82.6  1.7455    5  403     14.7   
423  7.05042   0.0  18.10     0  0.614  85.1  2.0218   24  666     20.2   
98   0.08187   0.0   2.89     0  0.445  36.9  3.4952    2  276     18.0   
455  4.75237   0.0  18.10     0  0.713  86.5  2.4358   24  666     20.2   
216  0.04560   0.0  13.89     1  0.550  56.0  3.1121    5  276     16.4   

          B  LSTAT  
254  392.89   6.57  
348  390.94   5.99  
476  396.21  18.68  
321  396.90   6.87  
326  396.90   6.15  
..      ...    ...  
155   88.01  15.02  
423    2.52  23.29  
98   393.53   3.57  
455   50.92  18.13  
216  392.80  13.51  

[404 rows x 12 columns]

In [20]:
# for option:3 compute the median using pandas DataFrame.median() function. 

#   1. add median i.e. median = housing['RM'].median()
#   2. specify median in fillna. i.e. housing.fillna(median)

median = housing["RM"].median() #option: 3

median

6.209

In [21]:
housing["RM"].fillna(median)

254    6.108
348    6.635
476    6.484
321    6.376
326    6.312
       ...  
155    6.152
423    6.103
98     7.820
455    6.525
216    5.888
Name: RM, Length: 404, dtype: float64

In [22]:
housing.shape

(404, 13)

In [23]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy = "median")

imputer.fit(housing)

SimpleImputer(strategy='median')

In [24]:
imputer.statistics_

array([2.86735e-01, 0.00000e+00, 9.90000e+00, 0.00000e+00, 5.38000e-01,
       6.20900e+00, 7.82000e+01, 3.12220e+00, 5.00000e+00, 3.37000e+02,
       1.90000e+01, 3.90955e+02, 1.15700e+01])

In [25]:
X = imputer.transform(housing)
X

array([[4.81900e-02, 8.00000e+01, 3.64000e+00, ..., 1.64000e+01,
        3.92890e+02, 6.57000e+00],
       [1.50100e-02, 8.00000e+01, 2.01000e+00, ..., 1.70000e+01,
        3.90940e+02, 5.99000e+00],
       [4.87141e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.96210e+02, 1.86800e+01],
       ...,
       [8.18700e-02, 0.00000e+00, 2.89000e+00, ..., 1.80000e+01,
        3.93530e+02, 3.57000e+00],
       [4.75237e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        5.09200e+01, 1.81300e+01],
       [4.56000e-02, 0.00000e+00, 1.38900e+01, ..., 1.64000e+01,
        3.92800e+02, 1.35100e+01]])

In [26]:
housing_tr = pd.DataFrame(X, columns=housing.columns)

In [27]:
housing_tr.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.278609   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.712366   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.878750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.209000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630000   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

# Sci-kit learn Design

### Primarily, three types of objects
    1. Estimators - it estimates some parameter based on a dataset. Eg. Imputer.It has a fit method and transform method.fit method- fits the dataset and calculates internal parameters

    2. transformers- takes input and return output based on the learning from fit(). It also has a convenience function called fit_transform() which fit and then transform

    3. Pridictiors- LinearRegression model is an example of predictor. fit() and predict() are two common functions. It also gives score() function which will evaluate the predictions.

### Feature Scaling

### Creating a pipeline

In [28]:
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import StandardScaler

my_pipeline= Pipeline([
    ('imputer', SimpleImputer(strategy="median")),
    ('std_scaler', StandardScaler())
])

In [29]:
housing_num_tr = my_pipeline.fit_transform(housing)
                                        

In [30]:
housing_num_tr.shape

(404, 13)

## Selecting a desired model for Roy Real Estate

In [31]:
# Random Forest Regression

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(housing_num_tr, housing_labels)

RandomForestRegressor()

In [32]:
some_data = housing.iloc[:5]

In [33]:
some_labels = housing_labels[:5]


In [34]:
prepared_data = my_pipeline.transform(some_data)

In [35]:
model.predict(prepared_data)

array([22.463, 25.471, 16.331, 23.488, 23.459])

In [36]:
list(some_labels)

[21.9, 24.5, 16.7, 23.1, 23.0]

## Evaluating the model

In [37]:
from sklearn.metrics import mean_squared_error
housing_predictions = model.predict(housing_num_tr)
lin_mse = mean_squared_error(housing_labels, housing_predictions)
lin_rmse = np.sqrt(lin_mse)

In [38]:
lin_rmse

1.1634295517057218

## Using better evaluation technique- cross validation

In [39]:
#1 2 3 4 5 6 7 8 9 10

from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, housing_num_tr, housing_labels, scoring="neg_mean_squared_error", cv =10)
rmse_scores = np.sqrt(-scores)

In [40]:
rmse_scores

array([2.77806021, 2.72924632, 4.37720047, 2.53091732, 3.3315517 ,
       2.6303775 , 4.76386489, 3.33641865, 3.34755642, 3.19442273])

In [41]:
def print_scores(scores):
    print("Scores: ", scores)
    print("Mean: ", scores.mean())
    print("Standard Deviation: ", scores.std())

In [42]:
print_scores(rmse_scores)

Scores:  [2.77806021 2.72924632 4.37720047 2.53091732 3.3315517  2.6303775
 4.76386489 3.33641865 3.34755642 3.19442273]
Mean:  3.301961620269954
Standard Deviation:  0.7040608050208857


# saving the model

In [43]:
from joblib import dump, load
dump(model, 'roy_estate.joblib') 

['roy_estate.joblib']

## Testing the model on test data

In [44]:
X_test = strat_test_set.drop("MEDV", axis=1)
y_test = strat_test_set["MEDV"].copy()
X_test_prepared = my_pipeline.transform(X_test)
final_predictions = model.predict(X_test_prepared)
final_mse = mean_squared_error(y_test, final_predictions)
final_rmse = np.sqrt(final_mse)


In [45]:
final_rmse

2.913198895359115

In [46]:
#print(final_predictions, list(y_test)) 

In [47]:
prepared_data[0]

array([-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.23979304, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034])

## using the model

In [48]:
from joblib import dump, load
model = load('roy_estate.joblib')
import numpy as np
features = np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.23979304, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])
model.predict(features)


array([22.463])